<?php ?>
<hr />
<center>&copy; <?php echo date('Y');?> <a href="/">Kill The Landline</a>. All rights reserved. </center>
  </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.js"></script>
  

  </body>
</html>
<?php ?>